# This is a basic workflow to help you get started with Actions

name: Test workflow for Continous Integration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "modularizing-the-pipeline-code" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1 : Check out code from repository
      - name : Check out code
        uses: actions/checkout@v4

      # Step 2 : Set up Python Environment
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.11'

      # Step 3 : Install all the dependencies
      - name: Install Dependencies 
        run: 
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4 : Run Tests
      - name: Run Tests
        run: pytest